config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user) 
      redirect_to tasks_path
    else
      flash.now[:danger] = 'ログイン失敗・・・'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :login_check
  def home
    
  end
  
  private
    def login_check
      if logged_in?
        redirect_to tasks_path
      end 
    end 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @tasks = Task.where(user_id: current_user.id)
        @task = Task.new
        @user = User.find(current_user.id)
    end 

    def create
        @task = Task.create(task_params)
        redirect_to tasks_path
    end
    
    def edit
        @task = Task.find(params[:id])
        if @task.user_id != current_user.id
            redirect_to tasks_path
        end
    end
    
    def update
        @task = Task.find(params[:id])
        if @task.user_id != current_user.id
            redirect_to tasks_path
        end
        @task.update(task_params)
        redirect_to tasks_path
    end
    
    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to tasks_path
    end

    
    private
        def task_params
          params.require(:task).permit(:title,:user_id)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ようこそ！！！！！"
      redirect_to tasks_path
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <h1>
    <% if logged_in? %>
      <%= link_to "SimpleToDo", tasks_path %>
    <% else %>
      <%= link_to "SimpleToDo", root_path %>
    <% end %>
    
  </h1>
  <nav>
    <ul>
      <% if logged_in? %>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="static_pages">
    <div class="welcome">
        <h1>Welcome!!</h1>
        <div class="login_action">
            <p><%= link_to "Login", login_path %></p>
            <p><%= link_to "NewUser", signup_path %></p>
        </div>
    </div>
    
</div>

app/views/tasks/edit.html.erb
<div class="edit_pages">
  <div class="edit_area">  
    <%= form_for(@task) do |f| %>
      <div><%= f.text_field :title, class: "title_text" %></div>
      <div><%= f.submit :class=>"edit_btn" %></div>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="task_pages">
  <div class="task_area">
    <table>
      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td class="title_td"><%= task.title %></td>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
            <td><%= link_to 'Delete', task_path(task), method: :delete %></td>
          </tr>
          <tr>
            <td><hr><td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= form_for(@task) do |f| %>
      <div><%= f.text_field :user_id , value: @user.id , type: "hidden"%></div>
      <div><%= f.text_field :title, class: "title_text" %></div>
      <div><%= f.submit :class=>"create_btn" %></div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="flex_box">
    <div class="form_area">
        <h1>Sign up</h1>
        <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
            <table>
                    <tbody>
                    <tr>
                        <th><%= f.label :name %></th>
                        <td><%= f.text_field :name, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :email %></th>
                        <td><%= f.email_field :email, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :password %></th>
                        <td><%= f.password_field :password, class: 'form-control' %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :password_confirmation, "Confirmation" %></th>
                        <td><%= f.password_field :password_confirmation, class: 'form-control' %></td>
                    </tr>
                </tbody>
            </table>
            <div class="btn_area">
                <%= f.submit "Create my account", class: "btn btn-primary sign_button" %>
            </div>
        <% end %>
    </div>
</div>
    

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>